"""add status

Revision ID: 334136da63d7
Revises: a424c7ae5341
Create Date: 2024-08-17 15:12:51.828860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334136da63d7'
down_revision: Union[str, None] = 'a424c7ae5341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_categories_status'), 'categories', ['status'], unique=False)
    op.add_column('users', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_column('users', 'status')
    op.drop_index(op.f('ix_categories_status'), table_name='categories')
    op.drop_column('categories', 'status')
    # ### end Alembic commands ###
