"""add category3

Revision ID: a424c7ae5341
Revises: 185fb70bd27d
Create Date: 2024-08-17 14:45:48.641188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a424c7ae5341'
down_revision: Union[str, None] = '185fb70bd27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('createAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('categories', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('categories', sa.Column('userId', sa.Integer(), nullable=True))
    op.drop_constraint('categories_UserId_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['userId'], ['id'])
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'UserId')
    op.add_column('users', sa.Column('createAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createAt')
    op.add_column('categories', sa.Column('UserId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_UserId_fkey', 'categories', 'users', ['UserId'], ['id'])
    op.drop_column('categories', 'userId')
    op.drop_column('categories', 'updatedAt')
    op.drop_column('categories', 'createAt')
    # ### end Alembic commands ###
