"""add status1

Revision ID: 47a1a2bac8cd
Revises: 334136da63d7
Create Date: 2024-08-17 15:14:13.002214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a1a2bac8cd'
down_revision: Union[str, None] = '334136da63d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_categories_status', table_name='categories')
    op.alter_column('users', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_users_status', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.alter_column('users', 'status',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.create_index('ix_categories_status', 'categories', ['status'], unique=False)
    op.alter_column('categories', 'status',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
